version: '3'

services:
  python:
    container_name: backend
    build: ./backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend/app:/code/app
    networks:
      - backfront
    stdin_open: true
    tty: true

  reactjs:
    container_name: frontend
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/spotify-app/:/code/spotify-app
    networks:
      - backfront
    environment:
      - REACT_APP_API_FQDN=${REACT_APP_API_FQDN}
    stdin_open: true
    tty: true


networks:
  backfront:
    name: backfront
    driver: bridge
 