version: '3'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend/app:/code/app
    networks:
      - backfront
    stdin_open: true
    tty: true

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - '3000:80'
    networks:
      - backfront
    environment:
      - VITE_API_FQDN=${VITE_API_FQDN}
    stdin_open: true
    tty: true


networks:
  backfront:
    name: backfront
    driver: bridge
 